sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.17.1
script:
  - bundle exec rubocop
  - bundle exec rspec
services:
  - redis-server
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: acts_as_lockable
  on:
    tags: true
    repo: tareksamni/acts_as_lockable
